#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A AFVAW39842SAM
#PBS -N PanelPointwise
#PBS -q debug
#PBS -l select=1:ncpus=1:mpiprocs=1
#PBS -l walltime=00:10:00
#PBS -j oe
#
## Optional Directives ------------------------------------
#PBS -m be

cd $PBS_O_WORKDIR
source $HOME/.bashrc
source $HOME/.profile
bash clean.sh

module load pointwise/18.5R1
python run_pointwise.py
