#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A AFVAW39842SAM
#PBS -N TransientPanel
#PBS -q debug
#PBS -l select=1:ncpus=48:mpiprocs=48
#PBS -l walltime=0:10:00
#PBS -j oe
#
## Optional Directives ------------------------------------
#PBS -m be

cd $PBS_O_WORKDIR
source $HOME/.bashrc
source $HOME/.profile
mpiexec_mpt -n 30 python3 mpi_panel_transient.py 2>&1 > output.txt
