#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A AFVAW00262F03
#PBS -q debug
#PBS -l select=1:ncpus=48:mpiprocs=48
#PBS -l walltime=01:00:00
#PBS -j oe
#
## Optional Directives ------------------------------------
#PBS -m be

cd $PBS_O_WORKDIR
source $HOME/.bashrc
source $HOME/.profile
bash clean.sh
module load pointwise/18.5R1
time python tester.py
#time python optimizer.py
